import { Journal } from "./types";

export const MOCK_JOURNALS: Journal[] = [
  // ── Business (8 entries) ──────────────────────────────────────────────────
  {
    id: "jr-bus-01",
    title: "Consumer Behavior Shifts in the Philippine E-commerce Landscape: Post-Pandemic Analysis",
    authors: ["Dr. Evelyn G. Santos", "Prof. Mark Dominic Alcantara"],
    discipline: "Business",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "This study examines the evolving consumption patterns among urban Filipino consumers following the pandemic. Utilizing a mixed-methods approach with 500 respondents across Metro Manila, the paper identifies key drivers of digital loyalty, security concerns, and the integration of social commerce. The findings suggest that online purchasing behaviors developed during lockdown periods have solidified, though with an increasing demand for omnichannel validation.",
    download_url: "/mock-journals/consumer-behavior-shifts-philippines.pdf",
    volume: "Vol. 34",
    issue: "No. 1",
    page_range: "pp. 12–29"
  },
  {
    id: "jr-bus-02",
    title: "Micro, Small, and Medium Enterprises (MSMEs) Resilience and Digital Adoption in Visayas",
    authors: ["Dr. Carlos L. Magno", "Dr. Anita S. Ramirez", "Prof. James K. Lee"],
    discipline: "Business",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Digital transition has become a necessity for MSMEs in the Visayas region. This paper details the digital maturity level of 120 registered MSMEs, assessing the hurdles of digital payment onboarding, logistics integration, and digital marketing adoption. Results indicate that government-sponsored digital literacy programs significantly accelerate transition speed, leading to a measurable increase in monthly profit margins.",
    download_url: "/mock-journals/msmes-resilience-visayas.pdf",
    volume: "Vol. 34",
    issue: "No. 1",
    page_range: "pp. 30–45"
  },
  {
    id: "jr-bus-03",
    title: "Corporate Governance Standards and Financial Sustainability of Cooperatives in Mindanao",
    authors: ["Dr. Jose N. Ilustre", "Dr. Sarah Mae V. Tan"],
    discipline: "Business",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Mindanao agricultural cooperatives serve as crucial economic lifelines. This research evaluates the relationship between strict adherence to standard corporate governance metrics and long-term financial sustainability. Through correlation analysis of audit data from 80 cooperatives over five years, the authors find that board diversity and regular external auditing positively correlate with solvency indices and capital accumulation.",
    download_url: "/mock-journals/governance-mindanao-cooperatives.pdf",
    volume: "Vol. 32",
    issue: "No. 2",
    page_range: "pp. 88–104"
  },
  {
    id: "jr-bus-04",
    title: "Green Supply Chain Management Practices in the Philippine Food Processing Sector",
    authors: ["Dr. Rachel G. Hizon"],
    discipline: "Business",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Faced with environmental challenges, food manufacturers are incorporating eco-friendly policies. This study surveys 45 food processing companies in Calabarzon regarding green procurement, eco-design, and waste reduction. The research reveals that while initial setup costs are high, the adoption of circular economy protocols reduces overhead costs by 15% in the long term, while boosting brand reputation.",
    download_url: "/mock-journals/green-supply-chain-food.pdf",
    volume: "Vol. 32",
    issue: "No. 3",
    page_range: "pp. 115–130"
  },
  {
    id: "jr-bus-05",
    title: "The Impact of Gig Economy Participation on Financial Well-being of Metro Manila Youth",
    authors: ["Prof. Patricia Coleen Cruz", "Dr. Ramon B. Ocampo"],
    discipline: "Business",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Freelance gig platforms offer high flexibility but minimal social safety nets. This study investigates the economic vulnerability and wealth-building capacities of 300 young gig workers. The paper highlights the lack of insurance and structured savings plans, recommending policy interventions for mandatory micro-insurance programs targeted at freelance operators.",
    download_url: "/mock-journals/gig-economy-manila-youth.pdf",
    volume: "Vol. 30",
    issue: "No. 1",
    page_range: "pp. 40–56"
  },
  {
    id: "jr-bus-06",
    title: "Tourism Rebound Strategies in the Visayas: Navigating Quality Assurance Guidelines",
    authors: ["Dr. Maria Clarissa Villa"],
    discipline: "Business",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Re-establishing tourism after economic disruptions requires strict health and service quality compliance. This study evaluates standard operating procedures implemented by Cebu hotels. The analysis demonstrates that transparent health-safety certifications significantly impact booking confidence, presenting a framework for regional tourism boards to unify accreditation.",
    download_url: "/mock-journals/tourism-rebound-visayas.pdf",
    volume: "Vol. 30",
    issue: "No. 2",
    page_range: "pp. 102–119"
  },
  {
    id: "jr-bus-07",
    title: "Inflationary Pressures and Pricing Adaptations of Public Markets in Luzon",
    authors: ["Prof. Ricardo D. Reyes", "Dr. Helen Grace Lim"],
    discipline: "Business",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Luzon wet markets struggle with rapid supply price increases. This paper explores the micro-level pricing strategies of independent vendors, including portion adjustments and micro-credits. The findings point to localized informal credit structures acting as buffer zones, shielding low-income consumers from immediate price shocks.",
    download_url: "/mock-journals/inflationary-pressures-luzon.pdf",
    volume: "Vol. 28",
    issue: "No. 1",
    page_range: "pp. 5–22"
  },
  {
    id: "jr-bus-08",
    title: "Digital Banking Penetration and Financial Inclusion in Rural Luzon Communities",
    authors: ["Dr. Jonathan K. Go", "Prof. Michelle Angela Ortiz", "Dr. Samuel T. Cruz"],
    discipline: "Business",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Although digital banks offer accessible services, rural populations maintain traditional savings methods. This research assesses the barriers to digital bank adoption in farming towns in Central Luzon. Lack of internet reliability and low trust in virtual interfaces are identified as primary hurdles, emphasizing the need for agent-assisted physical touchpoints.",
    download_url: "/mock-journals/digital-banking-inclusion.pdf",
    volume: "Vol. 28",
    issue: "No. 2",
    page_range: "pp. 67–82"
  },

  // ── Technology (8 entries) ────────────────────────────────────────────────
  {
    id: "jr-tech-01",
    title: "A Blockchain-Based Document Verification System for Philippine Higher Education Institutions",
    authors: ["Prof. Raymond G. Blanco", "Dr. Catherine P. Valencia"],
    discipline: "Technology",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Academic credential forgery poses a challenge to local universities. This paper proposes a decentralized, secure document verification network utilizing Ethereum smart contracts. By hashing and storing diploma keys on-chain, employers can instantly verify applicant records without requesting physical transcripts, reducing processing cycles from weeks to seconds.",
    download_url: "/mock-journals/blockchain-document-verification.pdf",
    volume: "Vol. 34",
    issue: "No. 1",
    page_range: "pp. 46–62"
  },
  {
    id: "jr-tech-02",
    title: "IoT-Enabled Soil Moisture and Nutrient Monitoring System for Precision Rice Farming",
    authors: ["Dr. Ferdinand M. Ramos", "Prof. Arthur P. Dizon", "Engr. Clara J. Santos"],
    discipline: "Technology",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Optimizing water and fertilizer use is critical for local rice farmers. This study designs and deploys low-cost LoRaWAN soil sensors in Nueva Ecija farms. The telemetry data drives a mobile application advising irrigation schedules. Field tests demonstrate a 20% reduction in water waste and a 12% improvement in crop yield over two planting cycles.",
    download_url: "/mock-journals/iot-precision-rice-farming.pdf",
    volume: "Vol. 34",
    issue: "No. 2",
    page_range: "pp. 110–127"
  },
  {
    id: "jr-tech-03",
    title: "Natural Language Processing (NLP) Tools for Sentiment Classification in Philippine Languages",
    authors: ["Dr. Jose Marie V. Ocampo", "Prof. Dennis T. Ferrer"],
    discipline: "Technology",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Analyzing public opinion in localized social media contexts requires models that handle code-switching (Taglish). This study builds a fine-tuned BERT transformer model trained on tag-swapped datasets. The model outperforms generic multilingual classifiers in classifying sentiment by 18%, providing a robust framework for local sentiment tracking.",
    download_url: "/mock-journals/nlp-sentiment-philippines.pdf",
    volume: "Vol. 32",
    issue: "No. 3",
    page_range: "pp. 142–159"
  },
  {
    id: "jr-tech-04",
    title: "Cybersecurity Maturity Assessments of Local Government Units (LGUs) in the National Capital Region",
    authors: ["Dr. Angela Marie L. Pineda"],
    discipline: "Technology",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Municipal networks are frequent targets for database intrusions. This paper assesses the cybersecurity postures of 10 LGUs in NCR using the NIST framework. Significant vulnerabilities are identified in access control policies and employee threat awareness training, motivating the creation of a unified regional IT security protocol.",
    download_url: "/mock-journals/cybersecurity-maturity-lgus.pdf",
    volume: "Vol. 32",
    issue: "No. 4",
    page_range: "pp. 200–218"
  },
  {
    id: "jr-tech-05",
    title: "Predictive Analytics Models for Typhoon Damage Estimation on Regional Power Grids",
    authors: ["Dr. Eric C. Cruz", "Dr. Melissa D. Gines", "Engr. Roberto M. Silva"],
    discipline: "Technology",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Predicting transmission line failures before landfall helps electrical cooperatives allocate post-storm repair teams. This project constructs an artificial neural network combining wind velocity vector maps and topological details. Validation using historical typhoon datasets shows 85% accuracy in pinpointing localized line breakages.",
    download_url: "/mock-journals/predictive-typhoon-damage-grids.pdf",
    volume: "Vol. 30",
    issue: "No. 2",
    page_range: "pp. 120–136"
  },
  {
    id: "jr-tech-06",
    title: "Design and Evaluation of Mobile Telehealth Solutions for Geographically Isolated Areas",
    authors: ["Dr. Sonia P. De Vega", "Prof. Kevin Andrew Ruiz"],
    discipline: "Technology",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Isolated island municipalities lack specialist consultation facilities. This paper evaluates a telehealth software running on low-bandwidth networks. By compressing diagnostic feeds and enabling asynchronous query queues, the tool allowed local health units to diagnose critical cardiology cases with remote specialists.",
    download_url: "/mock-journals/telehealth-isolated-areas.pdf",
    volume: "Vol. 30",
    issue: "No. 3",
    page_range: "pp. 167–184"
  },
  {
    id: "jr-tech-07",
    title: "Transitioning to Cloud Infrastructures: Case Studies of Selected Philippine Universities",
    authors: ["Prof. Ramon C. Singson"],
    discipline: "Technology",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "The move to online learning highlighted the weaknesses of on-premise servers. This research presents the technical roadmaps of three large universities migrating to cloud hosting. The study documents cost-benefit matrices, downtime events, and user authentication integrations, outlining recommendations for university CIOs.",
    download_url: "/mock-journals/cloud-transition-universities.pdf",
    volume: "Vol. 28",
    issue: "No. 2",
    page_range: "pp. 95–112"
  },
  {
    id: "jr-tech-08",
    title: "Automated Phytochemical Screening of Medicinal Plants Using Computer Vision Techniques",
    authors: ["Dr. Grace Victoria Lopez", "Dr. Samuel B. Tan", "Engr. Patricia M. Aquino"],
    discipline: "Technology",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Traditional chemical identification of herbal leaves is time-consuming. This paper introduces a convolutional neural network designed to identify active compounds via colorimetric leaf analysis. Testing on 15 local medicinal plants indicates 92% classification consistency matching laboratory chromatography checks.",
    download_url: "/mock-journals/automated-phytochemical-screening.pdf",
    volume: "Vol. 28",
    issue: "No. 3",
    page_range: "pp. 154–171"
  },

  // ── Education (8 entries) ─────────────────────────────────────────────────
  {
    id: "jr-edu-01",
    title: "AI Chatbots in Graduate Education: Assessment Redesign and Ethics Integration",
    authors: ["Dr. Eleanor Vance", "Dr. Robert Chen", "Dr. Amanda Reyes"],
    discipline: "Education",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "With the proliferation of Large Language Models, traditional research essay assignments face academic integrity threats. This paper analyzes curriculum redesigns across 12 graduate programs. By integrating structured oral defenses, reflective research logs, and software tracking protocols, deans can assess critical thinking directly rather than relying on written proxies.",
    download_url: "/mock-journals/ai-chatbots-graduate-education.pdf",
    volume: "Vol. 34",
    issue: "No. 1",
    page_range: "pp. 1–11"
  },
  {
    id: "jr-edu-02",
    title: "Research Advisership Competencies and Thesis Completion Rates in State Universities",
    authors: ["Dr. Felicia Singson", "Dr. Jonathan Reyes"],
    discipline: "Education",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Prolonged graduation rates among master's candidates are often linked to advisor interaction quality. This study gathers feedback from 400 graduate students in Luzon regarding advisory patterns. Using regression modeling, the paper shows that systematic feedback intervals and clear milestones predict completion within prescribed program timelines.",
    download_url: "/mock-journals/research-advisership-competencies.pdf",
    volume: "Vol. 34",
    issue: "No. 2",
    page_range: "pp. 63–78"
  },
  {
    id: "jr-edu-03",
    title: "Adapting Quality Assurance Standards to Hybrid Higher Education: Institutional Roadmaps",
    authors: ["Dr. Elizabeth Vance", "Dr. Samuel L. Giger"],
    discipline: "Education",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Accreditation guidelines designed for physical classrooms require modifications to assess hybrid configurations. This paper analyzes self-evaluation reports from 15 universities, identifying gaps in monitoring student engagement, virtual library services, and digital assessment integrity. A hybrid QA framework is proposed.",
    download_url: "/mock-journals/hybrid-qa-standards.pdf",
    volume: "Vol. 32",
    issue: "No. 1",
    page_range: "pp. 1–15"
  },
  {
    id: "jr-edu-04",
    title: "Mental Health and Resilience Profiles of Graduate School Students in Post-Pandemic Contexts",
    authors: ["Dr. Anita de Leon", "Dr. Sylvia Ramos"],
    discipline: "Education",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Graduate school students often balance heavy professional loads with academic requirements. This paper assesses anxiety and burnout levels of 250 master's and doctoral students using standardized scales. Results indicate high incidence of chronic stress, recommending institutional counseling services targeted at adult learners.",
    download_url: "/mock-journals/mental-health-resilience-graduate.pdf",
    volume: "Vol. 32",
    issue: "No. 2",
    page_range: "pp. 46–61"
  },
  {
    id: "jr-edu-05",
    title: "Accreditation Literacy Among Graduate School Deans and Department Chairs",
    authors: ["Dr. Luciana Vergara", "Dr. Henry G. Vance"],
    discipline: "Education",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Managing program documentation for institutional checks is a complex task. This study measures the level of accreditation understanding among 50 deans using custom questionnaires. The findings highlight significant training disparities between long-established universities and newly founded regional community colleges.",
    download_url: "/mock-journals/accreditation-literacy-deans.pdf",
    volume: "Vol. 30",
    issue: "No. 1",
    page_range: "pp. 23–39"
  },
  {
    id: "jr-edu-06",
    title: "Aligning Philippine Master of Science Syllabi with ASEAN Mobility Frameworks",
    authors: ["Dr. Arthur Pendelton", "Dr. Carlos Santos"],
    discipline: "Education",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "To facilitate credit transfer across Southeast Asia, Philippine institutions must align curricula with regional networks. This paper provides a cross-mapping analysis of three major master's programs against AUN-QA criteria, suggesting changes in credit allocation metrics.",
    download_url: "/mock-journals/syllabi-asean-mobility.pdf",
    volume: "Vol. 30",
    issue: "No. 2",
    page_range: "pp. 75–90"
  },
  {
    id: "jr-edu-07",
    title: "Developing Asynchronous LMS Platforms for Distant Graduate Classrooms",
    authors: ["Dr. Jeremy Brooks", "Dr. Yolanda Sayson"],
    discipline: "Education",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Asynchronous instruction enables professionals to pursue advanced studies without taking leaves. This paper models student achievement across various LMS course structures. The data shows that modular formats with clear checklists promote higher completion rates than open-ended resource directories.",
    download_url: "/mock-journals/lms-distant-classrooms.pdf",
    volume: "Vol. 28",
    issue: "No. 1",
    page_range: "pp. 23–40"
  },
  {
    id: "jr-edu-08",
    title: "Online Defense Protocols: Balancing Assessment Integrity and Technology Barriers",
    authors: ["Dr. Imelda Soriano", "Dr. Dolores Quambo"],
    discipline: "Education",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Conducting oral thesis defenses virtually introduces logistical and security challenges. This study compiles logs of 150 online defenses, discussing network interruptions, identity confirmation methods, and voting setups. A standardized virtual defense protocol is detailed.",
    download_url: "/mock-journals/online-defense-protocols.pdf",
    volume: "Vol. 28",
    issue: "No. 2",
    page_range: "pp. 41–58"
  },

  // ── Social Sciences (8 entries) ───────────────────────────────────────────
  {
    id: "jr-soc-01",
    title: "Climate Change Adaptation Stratagems of Coastal Communities in Southern Luzon",
    authors: ["Dr. Marites A. Aquino", "Prof. Roland J. Bautista"],
    discipline: "Social Sciences",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Coastal towns face increased storm severity. This research maps the adaptation mechanisms of 15 coastal barangays in Batangas. Through community focus groups, the study documents shifts in fishing patterns, local migration, and the deployment of traditional warning cues, illustrating the importance of community-led adaptation frameworks.",
    download_url: "/mock-journals/climate-adaptation-luzon.pdf",
    volume: "Vol. 34",
    issue: "No. 1",
    page_range: "pp. 79–94"
  },
  {
    id: "jr-soc-02",
    title: "Cultural Preservation Methods of the Mamanwa Tribe in Surigao Del Norte",
    authors: ["Dr. Lilia T. Castro", "Dr. Ronald P. Dizon"],
    discipline: "Social Sciences",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Modernization pressures affect indigenous cultural preservation. This ethnographic study documents the language, oral histories, and ritual ceremonies of the Mamanwa community. The authors argue that integrating tribal elders into local primary schools is key to preserving language fluency among youth.",
    download_url: "/mock-journals/cultural-preservation-mamanwa.pdf",
    volume: "Vol. 34",
    issue: "No. 2",
    page_range: "pp. 95–109"
  },
  {
    id: "jr-soc-03",
    title: "Socio-Economic Impacts of Urban Relocation Programs in Bulacan Communities",
    authors: ["Dr. Generoso S. Cruz", "Prof. Clara Mae N. Silva"],
    discipline: "Social Sciences",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Relocating informal settlers from metropolitan areas to suburban centers changes livelihood availability. This study compares household income and employment status before and after relocation. Results show a temporary decline in earnings, emphasizing the need for concurrent industrial development in housing sites.",
    download_url: "/mock-journals/socio-economic-impacts-bulacan.pdf",
    volume: "Vol. 32",
    issue: "No. 3",
    page_range: "pp. 160–175"
  },
  {
    id: "jr-soc-04",
    title: "Mental Health Discourses and Coping Mechanisms Among Filipino BPO Professionals",
    authors: ["Dr. Teresa R. Magsaysay", "Dr. Jeremy Brooks"],
    discipline: "Social Sciences",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Shift-work patterns in the BPO sector present psychological health challenges. This study surveys 350 call center agents regarding sleep hygiene, anxiety levels, and self-care strategies. The paper recommendations structured mental health modules integrated within corporate wellness policies.",
    download_url: "/mock-journals/mental-health-bpo-philippines.pdf",
    volume: "Vol. 32",
    issue: "No. 4",
    page_range: "pp. 219–234"
  },
  {
    id: "jr-soc-05",
    title: "Analyzing Indigenous Land Rights Conflicts in Select Areas of Cordillera Region",
    authors: ["Dr. Ramon Laurel", "Prof. Elena K. Sagmit"],
    discipline: "Social Sciences",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Overlapping land claims between government projects, mining companies, and ancestral lands lead to complex legal disputes. This research reviews landmark court filings in the Cordilleras, outlining strategies for aligning legal systems with tribal custom laws.",
    download_url: "/mock-journals/indigenous-land-rights-cordillera.pdf",
    volume: "Vol. 30",
    issue: "No. 3",
    page_range: "pp. 185–201"
  },
  {
    id: "jr-soc-06",
    title: "Women's Leadership Styles in Regional Local Government Administrations",
    authors: ["Dr. Sylvia Ramos", "Prof. Patricia Coleen Cruz"],
    discipline: "Social Sciences",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "This qualitative paper explores the experiences of women mayors in provincial Luzon. Key leadership characteristics include emphasis on participatory budgeting and disaster preparedness programs, presenting a leadership model for public administrators.",
    download_url: "/mock-journals/womens-leadership-local-government.pdf",
    volume: "Vol. 30",
    issue: "No. 4",
    page_range: "pp. 222–239"
  },
  {
    id: "jr-soc-07",
    title: "Community Resilience Frameworks in the Wake of Severe Super Typhoon Incidents",
    authors: ["Dr. Lino Reynoso", "Dr. Carlos Santos"],
    discipline: "Social Sciences",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Super typhoons require resilient local response models. This study evaluates recovery timelines of Samar municipalities. Communities with active neighborhood cooperation networks recovered basic services significantly faster, illustrating the value of social capital in disaster response.",
    download_url: "/mock-journals/community-resilience-typhoon.pdf",
    volume: "Vol. 28",
    issue: "No. 3",
    page_range: "pp. 172–189"
  },
  {
    id: "jr-soc-08",
    title: "Evaluating the Efficacy of Community-Based Rehabilitation Initiatives for Drug Surrenderers",
    authors: ["Dr. Alper Pineda", "Dr. Anita de Leon"],
    discipline: "Social Sciences",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "This study assesses the reintegration success rates of 180 rehabilitation participants. Key predictors of success include family involvement and local job placement. The authors provide suggestions for structuring municipal rehabilitation budgets.",
    download_url: "/mock-journals/community-rehabilitation-drug-surrenderers.pdf",
    volume: "Vol. 28",
    issue: "No. 4",
    page_range: "pp. 210–226"
  },

  // ── Others (8 entries) ────────────────────────────────────────────────────
  {
    id: "jr-oth-01",
    title: "Prevalence and Antimicrobial Resistance Profiles of Pathogens in Selected Metro Manila Water Outlets",
    authors: ["Dr. Ricardo M. Gomez", "Prof. Helen Grace Lim", "Dr. Catherine P. Valencia"],
    discipline: "Others",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Waterborne pathogens are a major health concern in urban areas. This microbiological study isolates and tests E. coli strains from major Metro Manila river channels. Results indicate high resistance levels to common first-line antibiotics, highlighting the need for improved urban wastewater treatment infrastructure.",
    download_url: "/mock-journals/pathogens-antimicrobial-manila.pdf",
    volume: "Vol. 34",
    issue: "No. 2",
    page_range: "pp. 128–144"
  },
  {
    id: "jr-oth-02",
    title: "Phytoremediation Potential of Local Fern Species in Copper Mine Tailings in Benguet Province",
    authors: ["Dr. Samuel T. Cruz", "Engr. Clara J. Santos"],
    discipline: "Others",
    convention_label: "54th PAGE National Convention",
    convention_slug: "54th-national-convention",
    year: 2024,
    abstract: "Reclaiming abandoned mining sites requires cost-effective methods. This research assesses the ability of Benguet fern species to accumulate heavy metals. The laboratory analysis shows high copper tolerance and accumulation rates in leaf tissues, suggesting these species are suitable for mine site rehabilitation.",
    download_url: "/mock-journals/phytoremediation-ferns-benguet.pdf",
    volume: "Vol. 34",
    issue: "No. 2",
    page_range: "pp. 145–160"
  },
  {
    id: "jr-oth-03",
    title: "Structural Engineering Integrity of Historical Brick Structures in Northern Luzon",
    authors: ["Engr. Roberto M. Silva", "Dr. Generoso S. Cruz"],
    discipline: "Others",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Spanish-era brick churches in Ilocos are vulnerable to seismic activity. This structural study models the load-bearing capacities of heritage brick walls. The authors recommend localized reinforcement techniques using lime-based mortars that preserve historical aesthetics while meeting safety requirements.",
    download_url: "/mock-journals/structural-integrity-brick-churches.pdf",
    volume: "Vol. 32",
    issue: "No. 4",
    page_range: "pp. 235–251"
  },
  {
    id: "jr-oth-04",
    title: "Air Quality Indexes and Respiratory Health of Street Vendors in Metro Manila",
    authors: ["Dr. Grace Victoria Lopez", "Dr. Marites A. Aquino"],
    discipline: "Others",
    convention_label: "53rd PAGE National Convention",
    convention_slug: "53rd-national-convention",
    year: 2023,
    abstract: "Prolonged exposure to vehicle emissions affects street vendors. This public health study measures particulate matter (PM2.5) levels at vendor sites alongside lung capacity tests. The data indicates a significant correlation between PM exposure and reduced lung capacity, recommending regular health checkups and protective masks.",
    download_url: "/mock-journals/air-quality-vendors-manila.pdf",
    volume: "Vol. 32",
    issue: "No. 4",
    page_range: "pp. 252–268"
  },
  {
    id: "jr-oth-05",
    title: "Analyzing Nutritional Quality of Traditional Rice Varieties in Cordillera Terraces",
    authors: ["Dr. Ferdinand M. Ramos", "Prof. Elena K. Sagmit"],
    discipline: "Others",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Traditional rice varieties have cultural and nutritional significance. This chemical analysis measures the protein, mineral, and antioxidant levels of Cordillera rice. The study shows higher zinc and iron content compared to commercial white rice, recommending support for heritage farming.",
    download_url: "/mock-journals/nutritional-quality-rice-cordillera.pdf",
    volume: "Vol. 30",
    issue: "No. 4",
    page_range: "pp. 240–255"
  },
  {
    id: "jr-oth-06",
    title: "Geotechnical Safety Mapping of Select Mountainous Routes in Benguet Province",
    authors: ["Engr. Patricia M. Aquino", "Dr. Ramon Laurel"],
    discipline: "Others",
    convention_label: "52nd PAGE National Convention",
    convention_slug: "52nd-national-convention",
    year: 2022,
    abstract: "Landslides during the rainy season threaten transport links. This geotechnical survey uses soil shear testing and slope models to map landslide susceptibility along Benguet routes, identifying priority areas for retaining wall construction.",
    download_url: "/mock-journals/geotechnical-safety-benguet.pdf",
    volume: "Vol. 30",
    issue: "No. 4",
    page_range: "pp. 256–271"
  },
  {
    id: "jr-oth-07",
    title: "Evaluating Municipal Solid Waste Management Strategies in Selected Cities in Luzon",
    authors: ["Dr. Samuel B. Tan", "Dr. Lino Reynoso"],
    discipline: "Others",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Rapid urbanization increases waste management demands. This comparative study evaluates recycling programs and landfill capacities in three Luzon cities. The findings suggest that neighborhood composting initiatives are effective in reducing waste volumes.",
    download_url: "/mock-journals/waste-management-luzon-cities.pdf",
    volume: "Vol. 28",
    issue: "No. 4",
    page_range: "pp. 227–242"
  },
  {
    id: "jr-oth-08",
    title: "Evaluating Wave Attenuation Qualities of Local Mangrove Forests in Samar Province",
    authors: ["Dr. Carlos Santos", "Prof. Ricardo D. Reyes"],
    discipline: "Others",
    convention_label: "51st PAGE National Convention",
    convention_slug: "51st-national-convention",
    year: 2021,
    abstract: "Mangrove forests serve as natural coastal barriers against storm surges. This environmental study models wave height reduction across varying mangrove densities in Samar. Results show that healthy forests can reduce wave energy by up to 60%, supporting mangrove restoration programs.",
    download_url: "/mock-journals/wave-attenuation-mangroves-samar.pdf",
    volume: "Vol. 28",
    issue: "No. 4",
    page_range: "pp. 243–259"
  }
];
