import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAnglesLeft,
  faAnglesRight,
  faArrowLeft,
  faArrowRight,
  faAward,
  faBuildingColumns,
  faBox,
  faCalendar,
  faChalkboardUser,
  faCheck,
  faCheckCircle,
  faCheckDouble,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faCircleCheck,
  faCircleXmark,
  faEllipsis,
  faEye,
  faEyeSlash,
  faPenToSquare,
  faFile,
  faFileArrowUp,
  faFileCircleXmark,
  faFilter,
  faFloppyDisk,
  faGraduationCap,
  faHourglassHalf,
  faInbox,
  faListCheck,
  faLock,
  faMagnifyingGlass,
  faMedal,
  faMinus,
  faPlus,
  faRotateLeft,
  faRightFromBracket,
  faStar,
  faTableList,
  faTrash,
  faBoxArchive,
  faUser,
  faUserCircle,
  faUserGraduate,
  faUserSlash,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
  faCalendar as faCalendarRegular,
  faCircleXmark as faCircleXmarkRegular,
  faClock as faClockRegular,
  faCircle as faCircleInfo,
  faFile as faFileRegular,
  faFloppyDisk as faFloppyDiskRegular,
  faSquareCheck as faSquareCheckRegular,
  faUser as faUserRegular,
} from "@fortawesome/free-regular-svg-icons";

let hasRegisteredFontAwesomeIcons = false;

export function registerFontAwesomeIcons() {
  if (hasRegisteredFontAwesomeIcons) {
    return;
  }

  library.add(
    faAnglesLeft,
    faAnglesRight,
    faArrowLeft,
    faArrowRight,
    faAward,
    faBuildingColumns,
    faBox,
    faCalendar,
    faChalkboardUser,
    faCheck,
    faCheckCircle,
    faCheckDouble,
    faChevronDown,
    faChevronUp,
    faChevronRight,
    faCircleCheck,
    faCircleXmark,
    faEllipsis,
    faEye,
    faEyeSlash,
    faPenToSquare,
    faFile,
    faFileArrowUp,
    faFileCircleXmark,
    faFilter,
    faFloppyDisk,
    faGraduationCap,
    faHourglassHalf,
    faInbox,
    faListCheck,
    faLock,
    faMagnifyingGlass,
    faMedal,
    faMinus,
    faPlus,
    faRotateLeft,
    faRightFromBracket,
    faStar,
    faTableList,
    faTrash,
    faBoxArchive,
    faUser,
    faUserCircle,
    faUserGraduate,
    faUserSlash,
    faUsers,
    faXmark,
    faCalendarRegular,
    faCircleXmarkRegular,
    faClockRegular,
    faFileRegular,
    faFloppyDiskRegular,
    faSquareCheckRegular,
    faUserRegular
  );

  hasRegisteredFontAwesomeIcons = true;
}

export {
  faAnglesLeft,
  faAnglesRight,
  faArrowLeft,
  faAward,
  faBuildingColumns,
  faBoxArchive,
  faCalendarRegular,
  faCheck,
  faCircleCheck,
  faGraduationCap,
  faChevronDown,
  faChevronUp,
  faEllipsis,
  faPenToSquare,
  faFileArrowUp,
  faMagnifyingGlass,
  faMinus,
  faPlus,
  faRotateLeft,
  faSquareCheckRegular,
  faTrash,
  faXmark,
  faFileRegular,
  faFloppyDiskRegular,
  faClockRegular,
  faUserRegular,
};
